[[library]]
name = "libamd"

[[library]]
name = "libbtf"

[[library]]
name = "libcamd"

[[library]]
name = "libccolamd"

[[library]]
name = "libcholmod"

[[library]]
name = "libcolamd"

[[library]]
name = "libklu"

[[library]]
name = "libldl"

[[library]]
name = "librbio"

[[library]]
name = "libspqr"

[[library]]
name = "libsuitesparseconfig"

[[library]]
name = "libumfpack"
